doc-warnings: no
test-warnings: no
strictness: veryhigh
max-line-length: 80
autodetect: yes
requirements:
    - requirements.txt
    - test-requirements.txt
ignore-paths:
    - doc
    - seedbox/db/sqlalchemy/migrate_repo
    - seedbox/torrent/bencode.py
    - setup.py
